### ISSUE TITLE
Cannot find module execa

### ISSUE THREAD

**Issue by jfretin** [turbothinh/network-speed-monitor#1]
Hello!

I wanted to try your project, but after docker-compose up, one of the container doesn't succeed at starting . It's the speedtest container. I have this error in the log:

 `
Error: Cannot find module 'execa'

Require stack:

- /src/index.js

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)

    at Function.Module._load (internal/modules/cjs/loader.js:667:27)

    at Module.require (internal/modules/cjs/loader.js:887:19)

    at require (internal/modules/cjs/helpers.js:74:18)

    at Object.<anonymous> (/src/index.js:1:15)

    at Module._compile (internal/modules/cjs/loader.js:999:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

    at Module.load (internal/modules/cjs/loader.js:863:32)

    at Function.Module._load (internal/modules/cjs/loader.js:708:14)

    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {

  code: 'MODULE_NOT_FOUND',

  requireStack: [ '/src/index.js' ]

}
`

I try to rebuild the container, no luck. I even deleted package-lock.json for forcing a full redownload of the npm libs, with no luck, always the same error.

Any idea?

**Comment by t18n** [comment]
Hi @jfretin . I forgot to uncomment a volume in `docker-compose`, so it overrode the `node_modules` in Dockerfile. It is now fix, you can run `git pull` inside the repo, then run `docker-compose up -d --build` to rebuild the image.

Alternatively, cd into `speedtest/src` and run `npm install` should also make it work. :)

**Comment by PalmaSolutions** [comment]
Had the same issue and fixed it with your recommendation, however the git pull would not work unless I removed influxdb/meta/meta.db.

Cheers!

**Comment by t18n** [comment]
Great that it works for you. I've tried to make another fix so that you don't have to delete `influxdb/meta/meta.db` manually anymore. Hope that works :D

**Comment by PalmaSolutions** [comment]
I deployed it with the manual deletion and it has been stably working for the past 12 hours. Thanks!

**Comment by jfretin** [comment]
Working on my side now! Removed meta.db + git pull. Thank you!
